#!/usr/bin/env bash
# Tests a single devcontainer feature in an isolated scratch copy of the repo's
# src/ and test/ trees so that savvy-web `installsAfter` entries can be
# stripped without touching the working tree. The devcontainer CLI rejects
# 3-segment OCI references it cannot resolve (e.g. ghcr.io/savvy-web/features/
# kcov before kcov has been published), and our scenarios test features in
# isolation anyway.
#
# Usage:
#   test-feature-isolated.sh <feature-id> [extra args passed to `devcontainer features test`]
#
# Env:
#   REPO_ROOT     Path to the repo root (defaults to `git rev-parse --show-toplevel`)
#   BASE_IMAGE    Base image for the autogenerated test (default ubuntu)
#   TEST_LOG      Path to write the raw CLI log (default /tmp/test.log)
#   RESULTS_JSON  Path to write parsed JSON results (default /tmp/test-results.json)
#
# Exit code:
#   0 if all scenarios passed, non-zero otherwise.

set -euo pipefail

ID="${1:-}"
shift || true
EXTRA_ARGS=("$@")

if [[ -z "$ID" ]]; then
  echo "Usage: $0 <feature-id> [extra-args...]" >&2
  exit 2
fi

REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel)}"
BASE_IMAGE="${BASE_IMAGE:-mcr.microsoft.com/devcontainers/base:ubuntu}"
TEST_LOG="${TEST_LOG:-/tmp/test.log}"
RESULTS_JSON="${RESULTS_JSON:-/tmp/test-results.json}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

FEATURE_JSON="${REPO_ROOT}/src/${ID}/devcontainer-feature.json"
if [[ ! -f "$FEATURE_JSON" ]]; then
  echo "[ERROR] Feature not found: src/${ID}" >&2
  exit 1
fi

if ! command -v devcontainer &>/dev/null; then
  echo "[ERROR] @devcontainers/cli is not installed." >&2
  echo "        Install it with: npm install -g @devcontainers/cli" >&2
  exit 1
fi

# Compute --skip-autogenerated from the *original* manifest, before stripping.
# Some features (e.g. package-manager) genuinely need their dep installed to
# pass the standalone autogenerated test.
SKIP_AUTOGENERATED=$(node -e "
  const j = JSON.parse(require('fs').readFileSync('${FEATURE_JSON}', 'utf8'));
  const deps = j.installsAfter || [];
  const ns = process.env.FEATURES_NAMESPACE || 'savvy-web/features';
  const prefix = 'ghcr.io/' + ns + '/';
  process.stdout.write(deps.some(d => typeof d === 'string' && d.startsWith(prefix)) ? 'true' : 'false');
")

SCRATCH=$(mktemp -d)
trap 'rm -rf "$SCRATCH"' EXIT

cp -R "${REPO_ROOT}/src" "${SCRATCH}/src"
cp -R "${REPO_ROOT}/test" "${SCRATCH}/test"

# Strip every feature's savvy-web installsAfter entries inside the scratch dir.
# We strip *all* features (not just the one under test) because scenarios may
# reference sibling features by local path, and the CLI resolves their
# manifests too.
for f in "${SCRATCH}/src"/*/devcontainer-feature.json; do
  node "${SCRIPT_DIR}/strip-installs-after.js" "$f"
done

ARGS=(-f "$ID" -i "$BASE_IMAGE" --skip-duplicated)
if [[ "$SKIP_AUTOGENERATED" == "true" ]]; then
  ARGS+=(--skip-autogenerated)
fi
ARGS+=("${EXTRA_ARGS[@]}")

set +e
devcontainer features test "${ARGS[@]}" "$SCRATCH" 2>&1 | tee "$TEST_LOG"
CLI_EXIT=${PIPESTATUS[0]}
set -e

node "${SCRIPT_DIR}/parse-test-results.js" "$TEST_LOG" "$RESULTS_JSON" \
  || echo '{"passed":[],"failed":[],"total":0,"allPassed":false}' > "$RESULTS_JSON"

if [[ "$CLI_EXIT" -ne 0 ]]; then
  exit "$CLI_EXIT"
fi

ALL_PASSED=$(node -e "
  try {
    const r = JSON.parse(require('fs').readFileSync('$RESULTS_JSON', 'utf8'));
    process.stdout.write(String(r.allPassed));
  } catch { process.stdout.write('false'); }
")

if [[ "$ALL_PASSED" != "true" ]]; then
  echo "[ERROR] devcontainer features test reported one or more failed scenarios." >&2
  exit 1
fi
