#!/usr/bin/env node
// Discovers features under ./src and outputs them in topological order based on
// `installsAfter` entries that resolve to local features in the savvy-web
// namespace. Each entry includes registry-publish status so the publish
// workflow can skip features whose current version is already published.
//
// Output (JSON, single line):
//   [
//     {
//       "id": "kcov",
//       "version": "0.1.0",
//       "path": "/abs/path/src/kcov",
//       "deps": [],
//       "skipAutogenerated": false,
//       "publish": true,
//       "reason": "Image does not exist in registry"
//     },
//     ...
//   ]
//
// Topological order means dependencies appear before their dependents — so
// publishing in this order guarantees that by the time a dependent feature is
// tested or published, its `installsAfter` references are already resolvable
// from the registry.
//
// Env:
//   GITHUB_REPOSITORY_OWNER  Org/user that owns the registry namespace.
//                            Defaults to "savvy-web".
//   FEATURES_NAMESPACE       Namespace path under the registry (e.g.
//                            "savvy-web/features"). Defaults to
//                            "<owner>/features".
//   SKIP_REGISTRY_CHECK      If "true", do not call `docker manifest inspect`;
//                            mark every feature publish=true. Use in PR CI
//                            where Docker may not be authenticated.

import { execSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve } from "node:path";

const owner = process.env.GITHUB_REPOSITORY_OWNER || "savvy-web";
const namespace = process.env.FEATURES_NAMESPACE || `${owner}/features`;
const skipRegistryCheck = process.env.SKIP_REGISTRY_CHECK === "true";
const featuresRoot = resolve(import.meta.dirname, "../../src");

const localPrefix = `ghcr.io/${namespace}/`;

const features = new Map();
for (const dirent of readdirSync(featuresRoot)) {
	const featureDir = join(featuresRoot, dirent);
	if (!statSync(featureDir).isDirectory()) continue;
	const jsonPath = join(featureDir, "devcontainer-feature.json");
	if (!existsSync(jsonPath)) continue;
	const data = JSON.parse(readFileSync(jsonPath, "utf8"));
	const installsAfter = Array.isArray(data.installsAfter) ? data.installsAfter : [];
	const localDeps = installsAfter
		.filter((d) => typeof d === "string" && d.startsWith(localPrefix))
		.map((d) => d.slice(localPrefix.length).split(":")[0].split("@")[0]);
	const skipAutogenerated = installsAfter.some((d) => typeof d === "string" && d.startsWith(localPrefix));
	features.set(data.id, {
		id: data.id,
		version: data.version,
		path: featureDir,
		deps: localDeps,
		skipAutogenerated,
	});
}

// Validate that every local dep refers to a feature that exists in src/.
for (const [id, f] of features) {
	for (const dep of f.deps) {
		if (!features.has(dep)) {
			throw new Error(`Feature '${id}' has installsAfter '${localPrefix}${dep}' but no src/${dep} directory exists.`);
		}
	}
}

// Kahn's algorithm — emit features whose deps are all already emitted.
const ordered = [];
const remaining = new Map(features);
while (remaining.size > 0) {
	const ready = [...remaining.values()]
		.filter((f) => f.deps.every((d) => !remaining.has(d)))
		.sort((a, b) => a.id.localeCompare(b.id));
	if (ready.length === 0) {
		const cycle = [...remaining.keys()].join(", ");
		throw new Error(`Dependency cycle detected among: ${cycle}`);
	}
	for (const f of ready) {
		ordered.push(f);
		remaining.delete(f.id);
	}
}

// Resolve registry publish status. Skipped in PR CI where Docker may not be
// authenticated against ghcr — those runs only need the matrix list.
for (const f of ordered) {
	if (skipRegistryCheck) {
		f.publish = true;
		f.reason = "Registry check skipped";
		continue;
	}
	const image = `ghcr.io/${namespace}/${f.id}:${f.version}`;
	try {
		execSync(`docker manifest inspect ${image}`, { stdio: "ignore" });
		f.publish = false;
		f.reason = "Image exists in registry (version unchanged)";
	} catch {
		f.publish = true;
		f.reason = "Image does not exist in registry";
	}
}

process.stdout.write(JSON.stringify(ordered));
