#!/usr/bin/env bash
# This test file is executed against an auto-generated devcontainer that
# installs the 'package-manager' feature with default options (packageManager=auto).
#
# NOTE: The auto-generated test is skipped for this feature in CI because
# package-manager requires the 'node' feature to be installed first
# (corepack is bundled with node). Use the scenarios in scenarios.json to
# test the meaningful option variants, which wire in node explicitly.
#
# Run scenarios with:
#   devcontainer features test -f package-manager --skip-autogenerated \
#     -i mcr.microsoft.com/devcontainers/base:ubuntu .

set -e

source dev-container-features-test-lib

check "corepack is installed" corepack --version

reportResults
