#!/usr/bin/env bash
set -euo pipefail

# Test a single devcontainer feature locally using the devcontainer CLI.
#
# Usage:
#   pnpm run test:feature <id>
#   pnpm run test:feature biome
#   pnpm run test:feature package-manager
#
# Requires:
#   - Docker running locally
#   - @devcontainers/cli: npm install -g @devcontainers/cli
#
# The devcontainer CLI builds a real container per scenario, runs the feature
# install, and executes the assertion scripts (test.sh + any scenario .sh
# files listed in scenarios.json). Output is per-scenario with clear
# pass/fail markers.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

ID="${1:-}"

if [[ -z "$ID" ]]; then
  echo "Usage: $0 <id>"
  echo ""
  echo "Examples:"
  echo "  $0 biome"
  echo "  $0 rust"
  echo "  $0 package-manager"
  echo ""
  echo "Available features:"
  find "${REPO_ROOT}/src" -mindepth 2 -maxdepth 2 -name "devcontainer-feature.json" \
    | sed "s|${REPO_ROOT}/src/||" \
    | sed 's|/devcontainer-feature.json||' \
    | sort \
    | sed 's|^|  |'
  exit 1
fi

FEATURE_JSON="${REPO_ROOT}/src/${ID}/devcontainer-feature.json"

if [[ ! -f "$FEATURE_JSON" ]]; then
  echo "[ERROR] Feature not found: src/${ID}" >&2
  echo "        Run '$0' without arguments to see available features." >&2
  exit 1
fi

if ! command -v devcontainer &>/dev/null; then
  echo "[ERROR] @devcontainers/cli is not installed." >&2
  echo "        Install it with: npm install -g @devcontainers/cli" >&2
  exit 1
fi

# Skip auto-generated test for features that depend on another local
# savvy-web feature (corepack/node must be wired in via scenarios).
SKIP_AUTOGENERATED=$(node -e "
  const j = JSON.parse(require('fs').readFileSync('${FEATURE_JSON}', 'utf8'));
  const deps = j.installsAfter || [];
  process.stdout.write(
    deps.some(d => d.includes('ghcr.io/savvy-web/')) ? 'true' : 'false'
  );
")

BASE_IMAGE="mcr.microsoft.com/devcontainers/base:ubuntu"
ARGS=(-f "$ID" -i "$BASE_IMAGE" --skip-duplicated)
if [[ "$SKIP_AUTOGENERATED" == "true" ]]; then
  ARGS+=(--skip-autogenerated)
fi

echo "[INFO] Testing feature: ${ID}"
echo ""

cd "${REPO_ROOT}"
devcontainer features test "${ARGS[@]}" .
